### ISSUE TITLE
Why does graphene.Enum resolves to enum.name as String?

### ISSUE THREAD

**Issue by ethankong113** [graphql-python/graphene#1094]
I have a field defined as a graphene enum:

```
class Color(enum.Enum):
  red = 1
  blue = 2


color = graphene.Field(
        type=graphene.Enum.from_enum(Color),
        required=True
    )
```

And when I try to run a query, this is what I get:

`
"data": {
  "color": "red"
}
`

It resolves to "red" instead of "Color.red". The documentation is not very clear on why a graphene enum would resolve into the enum.name

**Comment by Lacrymology** [comment]
I'm running into this as well, and it's frankly infuriating.

**Comment by erikwrede** [comment]
GraphQL enums resolve to their string names (e.g., "RED") in order to maintain a consistent and simple data format across different systems and clients. **This is by design**, and may differ from some of the languages you are used to. However, since there is a typed schema, you can always infer the type of the enum using the corresponding schema field.

Here's how it works the GraphQL way:

```graphql
enum Color {
  RED
  BLUE
}

type Query {
  color: Color
}
```

Querying for an enum field:

```graphql
query {
  color
}
```

Results in:

```json
{
  "data": {
    "color": "RED"
  }
}
```
