### ISSUE TITLE
Parsing of DateTime objects is too strict

### ISSUE THREAD

**Issue by crazyscientist** [graphql-python/graphene#1098]
Hi there,

being used to how I can filter `DateTime` objects in (Postre)SQL and Django using only a `Date` object, I kind of stepped into this small trap:

I have a Django model looking like this (stripped of irrelevant lines):

```python
class Request(Model):
    end_date = models.DateTimeField(null=True, default=None)
```

And my schema definition looking like this (stripped of irrelevant lines):

```python
class RequestType(DjangoObjectType):
    class Meta:
        model = models.Request
        interfaces = (graphene.relay.Node,)
        filter_fields = {
            "end_date": ["gt", 'lt'],
    }
```

Running such a query will be successful:

```
{
  requests(endDate_Gt: "2018-12-31T00:00:00"){
    edges{
      node{
        id
        endDate
      }
    }
  }
}
```

Being lazy and only typing the relevant part of the DateTime like this:
```
{
  requests(status_Name_Iexact:"accepted", kind: "RR", endDate_Gt: "2018-12-31"){
    edges{
      node{
        id
        endDate
      }
    }
  }
}
```
will cause an error:
```
{
  "errors": [
    {
      "message": "Argument \"endDate_Gt\" has invalid value \"2018-12-31\".\nExpected type \"DateTime\", found \"2018-12-31\".",
      "locations": [
        {
          "line": 2,
          "column": 67
        }
      ]
    }
  ]
}
```

In a strict manner of speaking this error certainly is correct, but it would be cool, if a string-date could be interpreted as a DateTime, too.

**Comment by denizdogan** [comment]
If we are to learn anything from Django REST Framework, we can note that DRF will not accept a date string for a datetime field with the message "Expected a datetime but got a date".

We certainly don't *have* to follow DRF's footsteps (and in some cases, probably shouldn't), but in my experience, dates and datetimes are inherently difficult to reason about and a common source of bugs.

I think the current behavior should be kept, possibly with a more descriptive message?

That being said, it shouldn't be too hard to make a new custom field definition that would accept either a date or a datetime, as long as your API consumers knows what they're doing and what it means to pass a date instead of a datetime, because it's not always obvious. Take a look at `graphene.types.datetime.DateTime` and `graphene.types.datetime.Date`, they're quite simple in their implementation.

I haven't tried this code, but I think it would be enough to do something like this:

```py
class DateOrDateTime(DateTime):

    @staticmethod
    def parse_value(value):
        if isinstance(value, datetime.date):
            return Date.parse_value(value)
        return DateTime.parse_value(value)
```

**Comment by crazyscientist** [comment]
I can't argue with your reasoning and your proposed _workaround_ would be sufficient.
