### ISSUE TITLE
Query taking too long to resolve. Take around 3 Minutes or so.

### ISSUE THREAD

**Issue by anilwarbhe** [graphql-python/graphene#1104]
I am using graphene with mongoengine (graphene-mongo).  I have 3000000 documents in the "products" collection. I want to paginate through products, so I am using following setup. It never returns the result. Why? I am doing something wrong here? Please suggest.
```
class ProductConnection(Connection):
    class Meta:
        node = ProductType

class ProductQuery():
    page_products = ConnectionField(ProductConnection)
    def resolve_page_products(self, info, **args):
        products = ProductsModel.objects.all()
        return products
```
When I use a query like:
```
{
  pageProducts(first:6){
    edges{
      node{
        title
        brand
      }
    }
    pageInfo{
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
```

**Comment by mjmonroe** [comment]
This line, `ProductsModel.objects.all()`, will get every product in ProductModels. MongoEngine is very slow because it instantiates every doc you retrieve. It will take forever to parse that many docs. Try [limiting](http://docs.mongoengine.org/guide/querying.html#limiting-and-skipping-results) the number of documents you are retrieving from Mongo and see how quickly it returns, `ProductsModel.objects[:10]`. If its quick, then that is your problem.

**Comment by melvinkcx** [comment]
I'm having some performance issue as well, try to use cProfile to look for the bottleneck

**Comment by asia653** [comment]
you're not using the `first: 6` in your query properly
