### ISSUE TITLE
graphene test client does not support async

### ISSUE THREAD

**Issue by dgarberj** [graphql-python/graphene#1147]
Does graphene plan to implement support for the test client making async requests?

**Comment by gaylonalfano** [comment]
@dgarberj I'm new to Graphene in general but after a bit of digging around I came across [this thread in FastAPI's Gitter](https://gitter.im/tiangolo/fastapi?at=5d19c94d490abf627a5428c6).

**TL;DR** - Inside your test function you can pass `executor=AsyncioExecutor()` to the `client.execute()` method. 

Here's a simple snippet from what I've setup. You'll notice that I have a `pytest` fixture set up inside `conftest.py` that uses Graphene's test `Client` called `graphql_client`. This way I don't have to import it inside my `test_main.py` file:
```python
# test_main.py
from graphql.execution.executors.asyncio import AsyncioExecutor
def test_main_graphql(graphql_client):
    executed = graphql_client.execute("""{ hello }""", 
    executor=AsyncioExecutor())
    assert executed == {"data": {"hello": "Hello stranger"}}
```
```python
# conftest.py for pytest
import pytest
from graphene.test import Client
from app.main import schema

@pytest.fixture(scope="module")
def graphql_client():
    return **Client(schema)**
```
```python
# main.py
import graphene
from graphql.execution.executors.asyncio import AsyncioExecutor
from fastapi import FastAPI
from starlette.graphql import GraphQLApp


class Query(graphene.ObjectType):
    # Define a Field 'hello' in our Schema with a single Argument 'name'
    hello = graphene.String(name=graphene.String(default_value="stranger"))

    # Resolver method takes GraphQL context (root, info) as well as
    # Argument (name) for the Field and returns data for the query Response
    async def resolve_hello(self, info, name):
        # We can make asynchronous network calls here
        return f"Hello {name}"


# Explicitly define schema so can use in conftest.py. There may be a better way.
schema = graphene.Schema(query=Query)
app = FastAPI()
app.add_route(
    "/", GraphQLApp(schema=schema, executor_class=AsyncioExecutor),
)
```
**Please note** I'm currently learning about FastAPI and its integration with Graphene (via Starlette) and wasn't sure whether to use Starlette's Test Client of Graphene's Client. There's a good chance that my code/setup isn't _best _practice_ so if you or others have suggestions I'm all ears. However, I was happy to learn that I could use Graphene's test `Client` with async since it seems more aligned with GraphQL terminology/naming conventions compared to Starlette's `TestClient`. Hope this helps!

**Comment by wbkdef** [comment]
ChatGPT 4 helped me get this working.  I'd recommend asking it, but here's the crux of how the test works:

`@pytest.mark.asyncio
async def test_async_resolver():
    client = Client(schema)
    executed = await client.execute_async('''{
        yourQuery {
            yourField
        }
    }''')`
