### ISSUE TITLE
How to use middleware for all queries?

### ISSUE THREAD

**Issue by datamusee** [graphql-python/graphene#1182]
Hello

I'm trying to use middlewares to do logging and to manage authorization. But I doen't find how to configure a middleware. 
I've a 
class Query(ObjectType):
... here some fields definition...

then
schema = Schema(query=Query)
vfonc = GraphQLView.as_view('graphql', schema=schema, graphiql=True)
flask_app.add_url_rule('/graphql', view_func=vfonc)
...
and I've 2 middlewares build after the model here:
https://docs.graphene-python.org/en/latest/execution/middleware/
But, that page describe how to add a middleware when you directly call schema.execute, which is an action that I never do.

I've read a lot (graphene  doc, stack overflow...)
I think that I've seen answers in the Django context, but not applicable in my context (Flask).

**Comment by deontaljaard** [comment]
@datamusee for Flask, you can register your middleware on the `as_view` function.

```python
GraphQLView.as_view("graphql", schema=schema, graphiql=True, middleware=[AuthMiddleware()])
````
I hope it helps.

**Comment by datamusee** [comment]
It helps.
Many thanks
I was unable to find such information

**Comment by Tatamethues** [comment]
@deontaljaard What about fastapi?

**Comment by daveflr** [comment]
https://github.com/graphql-python/graphene/issues/1182#issuecomment-614123819 I think this should be in the docs; otherwise, I couldn't find this info
btw I am having an issue with middleware, these are running multiple times per request, and also with resolvers too https://github.com/graphql-python/graphene/issues/1281#issue-736448167
