### ISSUE TITLE
Is there anyone can checkout pull request about "pageInfo"?

### ISSUE THREAD

**Issue by gwind** [graphql-python/graphene#123]
Hi, guys

I've submit a pull request https://github.com/graphql-python/graphene/pull/90 .
For fit requires of react/relay now.

thanks,

**Comment by syrusakbary** [comment]
Hi @gwind,
Sorry for taking too much time on this.

I didn't accepted the pull request because I thought the `camelCase` should be imposed everywhere or nowhere (having mixed cases in the same schema looks very weird).

As I'm not very convinced of what is the best path to choose I will accept the pull request. However this might change in the future.

**Comment by gwind** [comment]
Hi @syrusakbary 

Thank you for getting back to me.

I agree, my pull request is not a good idea. `realy.QL` have a confusion about pageInfo and it is unstable dev now. I'll used this in my local env with graphene.

Thanks again.
