### ISSUE TITLE
Cannot use Enums in mutations that are inside input types

### ISSUE THREAD

**Issue by federico-piazza** [graphql-python/graphene#1384]
* **What is the current behavior?**
Cannot use Enums in mutations that are inside input types. The input type never renders the field that was created as an enum.

While doing different attempts sometimes I get a duplicated type, like the one described in this issue:
https://github.com/graphql-python/graphene/issues/273

For example, when I define the enum as required:

```python
status = graphene.Enum.from_enum(ItemStatus)(required=True)
```
Then I get:

`
Found different types with the same name in the schema: ItemStatus, ItemStatus.
`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Below code describes a mutation that contains an input type and inside it an enum.

```python

class ItemStatus(models.TextChoices):
    NEW = 'new', 'New'
    PENDING = 'pending', 'Pending'
    COMPLETED = 'completed', 'Completed'

class Item(models.Model):
    name = models.CharField(max_length=255, blank=False)
    status = models.CharField(
        choices=ItemStatus.choices,
        default=ItemStatus.NEW
    )

class ItemType(DjangoObjectType):
    class Meta:
        model = Item
        fields = (
            'id',
            'status'
        )
       # status = graphene.Enum.from_enum(ActionItemStatus) # This works well only in types but not input types

class UpdateItemInput(graphene.InputObjectType):
    item_id = graphene.String(required=True)
    status = graphene.Enum.from_enum(ItemStatus)
    # If I define `status` as below, I get:
    # Found different types with the same name in the schema: ItemStatus, ItemStatus.
    # status = graphene.Enum.from_enum(ItemStatus)(required=True)

class UpdateItem(graphene.Mutation):
    class Arguments:
        input = UpdateItemInput(required=True)

    item = graphene.Field(ItemType)

```

* **What is the expected behavior?**
The expected behavior is that I can use enums inside a mutation input type

* **What is the motivation / use case for changing the behavior?**
Complex mutations use an input type wrapping all the input fields, we cannot do this for the moment.

* **Please tell us about your environment:**

  - Version: Python 3.9, Django 3.1.12, graphene 2.1.8
  - Platform: Mac OS  11.6

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

```
<html><head></head><body><h1>AssertionError
       at /graphql</h1>
  <pre class="exception_value">Found different types with the same name in the schema: ActionItemStatus, ActionItemStatus.</pre>
  

Request Method: | GET
-- | --
http://localhost:8000/graphql
3.1.12
AssertionError
Found different types with the same name in the schema: ActionItemStatus, ActionItemStatus.
/usr/local/lib/python3.9/dist-packages/graphene/types/typemap.py, line 97, in graphene_reducer
/usr/bin/python3
3.9.5
['/opt/project',  '/opt/project',  '/opt/project',  '/opt/.pycharm_helpers/pycharm_display',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/dist-packages',  '/usr/lib/python3/dist-packages',  '/opt/.pycharm_helpers/pycharm_matplotlib_backend']

</body></html>
```

**Comment by erikwrede** [comment]
The function `graphene.Enum.from_enum(ItemStatus)` uses `type` internally, which creates a new type object wrapping your enum every time it is called:
https://github.com/graphql-python/graphene/blob/master/graphene/types/enum.py#L55

See also:
https://docs.python.org/3/library/functions.html?highlight=type#type

This causes the `Found different types with the same name in the schema` exception that is thrown to you, because you created a duplicate type name. That is not allowed according to the GraphQL spec:
```All types within a GraphQL schema must have unique names. No two provided types may have the same name.```
(https://spec.graphql.org/June2018/#sec-Schema)

At this position in code, it is not really great to check for the existance of another type of the same name, since type implementation is not dependent on the actual schema definition. I think handling this issue from graphene itself (for example saving already converted enums for later reference) would cause more harm than good.

The cleanest solution for your problem would be to avoid the duplicate `from_enum` call from your altogether and define your enum on top level of your file like this:

`GQLItemStatus = graphene.Enum.from_enum(ItemStatus)`

and then reuse the enum definition as follows: 

```
class UpdateItemInput(graphene.InputObjectType):
    item_id = graphene.String(required=True)
    status = GQLItemStatus(required=True)
```

**Comment by federico-piazza** [comment]
@erikwrede thanks Erik, I'll test this and check if it works properly. I guess a good practice would be to use a django app name as part of the enum name, like `UserItemStatus`

**Comment by erikwrede** [comment]
Hey, did it work? If so, feel free to close the issue.
