### ISSUE TITLE
print(schema) does not include description

### ISSUE THREAD

**Issue by karmingc** [graphql-python/graphene#1443]
* **What is the current behavior?**
The schema can be printed with the mutations and queries, however, the description of each individual mutation and query is missing.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.
1. build your queries and mutations as usual
2. Add docstrings to your queries and mutations
3. print(schema)

* **What is the expected behavior?**
It should include the description. If we were to use introspection, the dict would include the description.

* **What is the motivation / use case for changing the behavior?**

Documentation.

* **Please tell us about your environment:**

  - Version: 2.1.9

**Comment by erikwrede** [comment]
Thanks for the report! 
Due to time constraints its currently hard to provide support for non-critical bug fixes in 2.x, especially given that this is a bug that shouldn't appear in 3.0. 

To get this fixed in time, it would really help if you could give some directions or try to find the root cause yourself. Happy to assist with a PR afterwards 🙂

**Comment by karmingc** [comment]
@erikwrede thank you for pointing that it's not up to date! I just noticed there was some incompatibility with flask-graphql, which is suggested to use `graphql-server[flask]` instead. Let me look into that!
