### ISSUE TITLE
Leading white spaces in description casuing issues

### ISSUE THREAD

**Issue by firaskafri** [graphql-python/graphene#1489]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**
Currently Scalar types and Field types pass `description` without touching it which is causing the issue of inconsistent white spaces in the case of multi-line descriptions when parsed by federation services.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.

1 - Add a multi-line description argument to any `Scalar` or `Field`
2 - Generate schema
3 - Try to build a service schema using [graphene-federation](https://github.com/graphql-python/graphene-federation)
4 - Connect the service to a federation gateway

* **What is the expected behavior?**

Leading white spaces in multi-line description must be stripped

* **What is the motivation / use case for changing the behavior?**
Building a federated gateway

* **Please tell us about your environment:**

  - Version: 
  - Platform: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by erikwrede** [comment]
Hey Firas, 
what exactly is the difference between the federation-stitched docstring and a docstring from pure graphene when looking at the schema? Why does this only apply to federated schemas and is it not desirable to add whitespace and indent to the docstrings sometimes?

Since GQL-docstrings are formatted in Markdown, stripping the whitespaces would remove features like lists with multiple levels of indentation:

* A
    * B
        * C
 
```markdown
* A
    * B
        * C
 ```
