### ISSUE TITLE
Plan for maintenance?

### ISSUE THREAD

**Issue by nickhudkins** [graphql-python/graphene#227]
Just wondering if I should simply maintain my own fork or if there are plans to keep this in spec / feature parity with other libraries in other languages. Understood if you can't do it alone, but maybe that means time for some more collaborators.

**Comment by syrusakbary** [comment]
Hi @nickhudkins!
First of all, thanks for raising your concerns.
I'm now involved in the next version of Graphene (1.0) that will improve a lot the code in the core.
With this version, both Django and SQLAlchemy integrations will be separated in other repos, so the collaborations will be easier to do and maintain.

Any PR to the main codebase will be always welcome.
I will add happily as collaborator/maintainer to anyone that contributes periodically into the framework.

**Comment by Globegitter** [comment]
Yep @nickhudkins, @syrusakbary has been pretty good so far with merging PRs and responding to issues as we have come across a few bugs while using graphene. So I think contributing to this repository rather than keeping a fork would be better for the community :)

**Comment by agilgur5** [comment]
It doesn't seem like there's a milestone or otherwise list of issues + features set for 1.0 (aside from the respective branch). I think that would be really good to have to promote + make contributions simpler, as well as to give a roadmap of things to expect for potential users.

Planning on integrating Graphene with our Django app (as it seems really simple to do so, props on the great work so far!) and some of the biggest concerns I see with this project are the lack of transparency and number of _core_ contributors/maintainers -- having a more defined upgrading process may help alleviate both. Hoping to have a great experience with this library soon :)

**Comment by syrusakbary** [comment]
The first stage of the Plan for maintenance is more clear now, so here's a heads up!

## Different repos

All the Graphene integrations are now separated into different repos. The docs are also in each repo, so maintaining and updating them is much easier now! :)

## Transparency and Core Contributors

As the integrations are now separated from the core, is easier to achieve better project permissions.
This integrations will have more transparency and core maintainers apart of myself. I have few people in mind for each of the integrations (excluding the ones that are already maintained and created by other people, like `graphene-gae` and `graphene-peewee`).

## Project priorities

Also, for the main repository, `graphene` we will take advantage of the new feature of Github -[Projects](https://github.com/graphql-python/graphene/projects)- and use it as board of the priorities for the project. Any idea will be discussed and we will decide as community what are the features we want graphene to have, while preserving compatibility and assuring a good path for the future!


PS: Graphene `1.0` will be released quite soon!

Please let me know if you have any other suggestion! :)

**Comment by jkimbo** [comment]
Closing this issue since the Django and SQLAlchemy integrations have been moved into separate repos now.
