### ISSUE TITLE
Unclear how to create a schema for an SqlAlchemy model with a One to One join.

### ISSUE THREAD

**Issue by hugoduncan** [graphql-python/graphene#246]
How does one create a schema for an SqlAlchemy model that contains a one-to-one join (i.e. a `relationship` where `uselist=False`)?

My attempts so far just result in `Resolved value from the connection field have to be iterable` errors.

**Comment by syrusakbary** [comment]
It seems to be a bug. Thanks for reporting :)

**Comment by hugoduncan** [comment]
Thanks for the rapid fix!   What's the difference between `next` (the branch to which this was committed) and `1.0`?

**Comment by syrusakbary** [comment]
`1.0` was the first approach of remaking the core of graphene, but after implementing it I realized I made some assumptions that were making the code less understandable and more coupled.
Because of that I created another branch `next` with a cleaner and more maintainable implementation.

## What are the main differences between `1.0` and `next`?
* `1.0` was coupling the `GraphQL` definition to the graphene type definition
* `next` separated this `graphene` to `GraphQL` conversion in a `TypeMap` definition.
* `next` is separating the Interfaces from `ObjectTypes`
* `next` have `AbstractType`s that could be inherited from any `Interface`, `ObjectType` or `InputObjectType`

Because of this reasons the `next` branch will be the one that `graphene` adopts for its next version: 1.0 (and the `1.0` current branch will replaced will `next`)

**Comment by syrusakbary** [comment]
`1.0.dev` is now in `master`.
Also is uploaded to PyPI (you can install it with `graphene-sqlalchemy>=1.0.dev`).
