### ISSUE TITLE
Dynamic ObjectType properties?

### ISSUE THREAD

**Issue by gijs** [graphql-python/graphene#336]
Hi,

I'm trying to get Graphene to return a GraphQL response for dynamically created SQL tables.

(The code I'm using so far is posted below)

Is there a way to dynamically specify the DatasourceType instead of having to hardcode it as a class?

Maybe an edge case but I thought I'd ask anyway.

Thanks, great library by the way!

Gijs

``` python
import graphene
from django.db import connection
from collections import namedtuple


class DatasourceType(graphene.ObjectType):

    id = graphene.String()
    COLUMN_A = graphene.String()
    COLUMN_B = graphene.String()
    COLUMN_C = graphene.String()


class QueryType(graphene.ObjectType):

    class Meta:
        name = 'Query'

    datasources = graphene.List(DatasourceType)

    def resolve_datasources(a, b, c, d):
        return get_datasources()


def get_db_rows(sql, args=None):
    cursor = connection.cursor()
    cursor.execute(sql, args)
    columns = [col[0] for col in cursor.description]
    RowType = namedtuple('Row', columns)
    data = [
        RowType(*row)
        for row in cursor.fetchall()]
    cursor.close()
    return data


def get_datasources():
    return get_db_rows("""SELECT * FROM "someschema"."sometable"
    """)


schema = graphene.Schema(query=QueryType)
```

**Comment by yfilali** [comment]
Do you mean you need to create the DatasourceType attributes from the result of another method call? If so then this should do the job:
```
def call_that_returns_fields_dict():
    result = {}
    for field in dynamicfields:
        result[field.name] = graphene.String()

    return result

DatasourceType = type('DatasourceType', (graphene.ObjectType,), call_that_returns_fields_dict())

```

If you mean to say you need to get the column names from your query as fields, then that means you will need to make the function above query the DB to find out the table's column names.

Btw, you should note that once you've created the schema, the fields will not and should not change. This is because the party querying your GraphQL API should not have the fields change on them at random per the spec. GraphQL only works when both the client and server agree on the schema.

**Comment by jkimbo** [comment]
Hi @gijs . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
