### ISSUE TITLE
ImportError at /api Could not import 'cookbook.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: type object 'Query' has no attribute 'name'. when trying to follow Django tutorial

### ISSUE THREAD

**Issue by reverie** [graphql-python/graphene#343]
I'm trying to follow the Django tutorial at http://docs.graphene-python.org/projects/django/en/latest/tutorial.html and getting the following error:

```
ImportError at /api
Could not import 'cookbook.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: type object 'Query' has no attribute 'name'.
```

Changing `AbstractType` to `ObjectType` seems to fix it, but I'm not sure if that's the right thing.

**Comment by rattrayalex** [comment]
I also hit this

**Comment by rattrayalex** [comment]
When I tried changing `AbstractType` to `ObjectType` and open `/graphql`, I get this error message: 

```
{
  "errors": [
    {
      "message": "Query fields must be a mapping (dict / OrderedDict) with field names as keys or a function which returns such a mapping."
    }
  ]
}
```

**Comment by rattrayalex** [comment]
I resolved by changing `class Query(cookbook.ingredients.Query, graphene.ObjectType):` to `class Query(cookbook.ingredients.Query, graphene.ObjectType):` in the top-level schema.

**Comment by syrusakbary** [comment]
This is fixed in [graphene-django](https://github.com/graphql-python/graphene-django) with this commit: https://github.com/graphql-python/graphene-django/commit/d1f28633744d61aa955dc862c5cd2c29d678695c

The [docs had an issue while doing the build](https://github.com/graphql-python/graphene-python.org/issues/8) so they haven't been automatically updated with each git commit, but I'm working on fixing that there.

Refer to the [graphene-python.org issue](https://github.com/graphql-python/graphene-python.org/issues/8) if you want to keep track of this.

Closing issue :)

**Comment by mahdyhamad** [comment]
I have the same problem!

**Comment by starascendin** [comment]
Still have the same issue

**Comment by ColeDCrawford** [comment]
Also hit this
