### ISSUE TITLE
Support for Google App Engine NDB

### ISSUE THREAD

**Issue by kiennt** [graphql-python/graphene#37]
@syrusakbary 

Do we have any plan to support google app engine ndb in near future?
If not, I am willing to help. 

Could you please guide me to which part I should start to do it?

Thanks

**Comment by jhgg** [comment]
Hi @kiennt - As it turns out, `graphene`, `graphql` and `graphql-epoxy` in general doesn't have a preference for what kind of database backend you use. Although `graphene` does come with built in support for the introspection of Django models to generate a Schema, you could easily just manually define your Schema & Types to fit your NDB entity schema.

**Comment by syrusakbary** [comment]
Hi @kiennt,

Yep, adding support for automatic Google App Engine NDB mapping to GraphQL would be great.
You can get inspired how `graphene` is doing with [Django models mapping](https://github.com/graphql-python/graphene/tree/master/graphene/contrib/django). Everything should be similar except of the converter (who have to be adapted for converting the fields from NDB), and `types.py` who also have to be adapted for getting the fields from the NDB model.

**Comment by cyrfer** [comment]
+1

**Comment by ekampf** [comment]
:+1:

**Comment by ekampf** [comment]
Hey @kiennt, @cyrfer  would love your feedback on https://github.com/ekampf/graphene-gae

**Comment by syrusakbary** [comment]
Closing this issue, as @ekampf did a terrific job with [graphene-gae](https://github.com/graphql-python/graphene-gae), which is now part of the GraphQL-Python community.

[Would be great to have a PR into this repo adding the docs into the website]

**Comment by ekampf** [comment]
docs PR in the works...
