### ISSUE TITLE
1.1.3 to 1.2.0 produces "Schema must contain unique types..."

### ISSUE THREAD

**Issue by ncrmro** [graphql-python/graphene#439]
This [repo](https://github.com/ncrmro/polymorphic_django_grapene_error
) is of a django project that demonstrates and error when upgrading graphene from 1.1.3 to 1.2.0 all other dependencies are frozen.

The following error is returned when running graphql_schema or any other executions on the schema

```
AssertionError: Schema must contain unique named types but contains multiple types named "SellOrderNode".
```

This [test report](https://circleci.com/gh/ncrmro/polymorphic_django_grapene_error/2
) shows the error.

Uses polymorphic models [polymorphic model](https://django-polymorphic.readthedocs.io/en/stable/
) and returns the items with unions

**Comment by hueypeard** [comment]
Hi, I had the issue and I was able to fix it with [this commit](https://github.com/hueypeard/graphene/commit/66ed1e1410acb72bd77974710536143199a188b4).

It seems that [the following lines](https://github.com/graphql-python/graphql-core/blob/master/graphql/type/typemap.py#L59-L62) in graphql-core don't correctly compare GrapheneGraphQLType types, due to no fault of graphql-core itself. To fix this and any other issues with GrapheneGraphQLTypes being equivalent, I simply added an `__eq__` comparison method to GrapheneGraphQLType to only compare the internal graphene_type and not the instances themselves.
```
if type.name in map:
  assert map[type.name] == type, (
    'Schema must contain unique named types but contains multiple types named "{}".'
  ).format(type.name)
````

I'd be happy to submit a pull request if this is, in fact, the correct way to go about solving this issue, but I can't say for sure due to my lack of experience with this library, so if any experienced graphene users can weigh in here please let me know.

**Comment by ncrmro** [comment]
@hueypeard thanks for the input, I'm not particularly versed on the internals myself (should probably do that anyway). I await the graphql teams input as well.

**Comment by ncrmro** [comment]
@hueypeard I can confirm copying the bit from your your posted solution does allow me to dump the schema.

**Comment by ncrmro** [comment]
So graphene-django requires 'graphene>=1.1.3' for one atm. When ipmletmening the __eq__ method querying graphql returns 

```
{
  "errors": [
    {
      "message": "unhashable type: 'GrapheneObjectType'"
    }
  ],
  "data": {
    "parts": null
  }
}
```

**Comment by syrusakbary** [comment]
Revising this now. Thanks for the report :)

**Comment by syrusakbary** [comment]
This is now fixed in master :).

I improved the `TypeMap` converter rather than modifying the `__eq__` in the `GrapheneGraphQLType` as it's more robust and fixes the issue directly rather than silence it.

**Comment by ncrmro** [comment]
@syrusakbary you're amazing, thank you so much!

**Comment by dfee** [comment]
Fortunately I came across this. Pinning to master works.
