### ISSUE TITLE
Unexpected import behaviour

### ISSUE THREAD

**Issue by jamesstidard** [graphql-python/graphene#441]
Hi,

I was using the this library and I was getting some quite hard to debug/reproduce behaviour. This took me and a nice guy from PyCharm a while to figure out.

The issue is that the library's imports seem to break depending on the file name. For example:

```python
# graphql.py
import graphene
graphene.ObjectType
```
```bash
$ python graphql.py

Traceback (most recent call last):
  File "graphql.py", line 1, in <module>
    import graphene
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/site-packages/graphene/__init__.py", line 19, in <module>
    from .types import (
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/site-packages/graphene/types/__init__.py", line 7, in <module>
    from .scalars import Scalar, String, ID, Int, Float, Boolean
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/site-packages/graphene/types/scalars.py", line 3, in <module>
    from graphql.language.ast import (BooleanValue, FloatValue, IntValue,
  File "/Users/jamesstidard/Desktop/graphql.py", line 2, in <module>
    graphene.ObjectType
AttributeError: module 'graphene' has no attribute 'ObjectType'
```

I've noticed this for files named both `graphql` and `graphene`. I assume it has to do with how graphene is handling its imports and `__init__.py`. I did try to have a look through it, but after already spending the time trying to debug it, and that the `__init__.py` in Graphene isn't your straight forward one, my brain is currently fried.

I can fix my project by simply renaming the model to something like `graph_ql.py`, though I thought it's worth reporting as a bug as other people may also have this problem. Also depending on what's causing this, there may be a chance even more generic things like `utils`.

Thanks for the library.

**Comment by lnlwd** [comment]
I have the same problem! I don't want to add the `_ql` suffix on all my files. This is terrible!

**Comment by alexisrolland** [comment]
Same problem here. Has anyone find a better solution to this?

**Comment by jkimbo** [comment]
There is not much we can do about this since this is how python's module resolution works. Graphene is based off [graphql-core](https://github.com/graphql-python/graphql-core) which is a port of the reference graphql server implementation [graphql-js](https://github.com/graphql/graphql-js). `graphql-core` installs itself as `graphql` so if you name a file `graphql.py` in your project python will pick that up first and any further imports to `graphql` will reference your local file and not the library `graphql-core`.

To avoid this issue I can only suggest that you name your graphql implementation as something other than the literal name "graphql" (or "graphene" for that matter).
