### ISSUE TITLE
Getting GeventExecutor and DataLoader to play nicely with each other

### ISSUE THREAD

**Issue by phil303** [graphql-python/graphene#488]
Disclaimer, this could be my misunderstanding how these two things should work together - I'm trying to get `DataLoader` to play nicely with `GeventExecutor` so that I can have requests to different services work in parallel. But I'm noticing that when I include `GeventExecutor` this doesn't happen and is actually breaking up what were originally batch requests via `some_loader.load_many` into individual ones.

My initial call into graphql is via the webob integration:
```python
serve_graphql_request(
    request,
    request.schema,
    executor=GeventExecutor(),
    context_value=GraphQLContext(),
)
```

An example resolver:
```python
class Query(graphene.ObjectType):
    trending_articles = graphene.List(of_type=Article)

    def resolve_trending_articles(self, args, context, info):
        ids = resolvers.get_trending_article_ids()
        return context.article_loader.load_many(ids)
```

And the relevant loader:
```python
class ArticleLoader(DataLoader):
    # article_ids is being set as a one item list for each id in the load_many call
    def batch_load_fn(self, article_ids):
        articles = article_service_client.get_articles(article_ids)
        return Promise.resolve([build_article(article) for article in articles])
```

`load_many` calls into `load` internally which, via the function call in the Promise object [here](https://github.com/syrusakbary/promise/blob/master/promise/dataloader.py#L72), is adding a loader object with the notion of the resolver into a queue. The part that I start to lose the thread on is what happens around [here](https://github.com/syrusakbary/promise/blob/master/promise/dataloader.py#L199). I believe the queue starts being drained but I'm unclear as to why this starts to happen immediately in the case of the GeventExecutor.

Any insight on this?

**Comment by syrusakbary** [comment]
Hi Phil!

The reason this is happening is because the DataLoader runs on top of the [promise loop engine](https://github.com/syrusakbary/promise/blob/master/promise/async_.py) instead of one based in gevent event loop.
So, the fields are resolved asynchronously, but the dataloader relies on the "next tick" of the event loop, which in this case is not Gevent's and therefore the ticks are triggered even before the Gevent next loop tick.

## Why creating an event loop?
In older versions of Python (2.7, 3.3) there was no event loop provided by default (asyncio was added in Python 3.4), and the easier way to have `Promise`s working in a universal way was to mimic the effects of an event loop.

## How to solve it
The way for fixing this is quite simple, by just making dataloader to push the job for batching to the Gevent loop instead of the custom one (`async_instance`).
https://github.com/syrusakbary/promise/blob/master/promise/dataloader.py#L199

I can assist you on that, if you need so!

**Comment by phil303** [comment]
Thanks Syrus
What you're saying makes total sense. Converting the line you mentioned to the following worked:

```python
def enqueue_post_promise_job(fn):
    global resolved_promise
    if not resolved_promise:
        resolved_promise = Promise.resolve(None)
    gevent.spawn(fn)
```

Which is awesome and what I expected looking at the code again with your reply in mind. But this is obviously not a very generic solution. What are your thoughts on how to do that? Naively, it seems like it'd be an overhaul for the Promise codebase.

**Comment by phil303** [comment]
Closing as this is fixed with the [Schedulers refactor](https://github.com/syrusakbary/promise/pull/37).
