### ISSUE TITLE
Release 1.5 Expectation

### ISSUE THREAD

**Issue by AshwinRamesh** [graphql-python/graphene#516]
Hi @syrusakbary what is the timeline for a v1.X release. There are many bug fixes which are hanging out in master, but unreleased.

Thanks in advance,

Ash

**Comment by syrusakbary** [comment]
Hi @AshwinRamesh, I'm open to create a `1.4.2` release with the changes, however I'm not sure which bug fixes you refer to as there are not a lot of bugfixes in `master` since the last release `1.4.1` (only relevant change in code is https://github.com/graphql-python/graphene/commit/f22504c2fc931007111264f4067e11662dd4ed13 )

https://github.com/graphql-python/graphene/commits/master

You were referring to this change or maybe other bugfixes of `2.0`?

**Comment by AshwinRamesh** [comment]
@syrusakbary Sorry for the confusion. I meant to post this on the graphene-django issues. The many-to-many bug (https://github.com/graphql-python/graphene-django/pull/181) etc. are items we are looking forward to in an official release. Also looking forward to 2.0 in all packages. Thanks!!

**Comment by jkimbo** [comment]
2.0 is out so I'm going to close this issue. If there are any specific bugs please open new issues for them.
