### ISSUE TITLE
How to make an OR/AND filtering

### ISSUE THREAD

**Issue by minrock** [graphql-python/graphene#528]
Hi Guys! I'm new using this library, and I have a question.

How can I join filters with and/or for the same filter for example, I'm using django-cities and I'll make a query that is like this in django ORM :

`Q(kind="PPLC") | Q(kind="PPLA")`

but when I try to do something like this in graphene, I do not know how I should do it, I found someone that shows how to and/or in graphql but that way does not work, the query was something like this translated to what I need :

`
{
    cities(filter: { "OR" : [ { "kind": "PPLC"}, { "kind": "PPLA" } ] }){
        <body>
    }
}
`

Also I tried to do a IN filter with django-filters agains what the documentation says:

`
filter_fields = {
            'country__name' : ['iexact', 'icontains'],
            'kind': ['in', 'iexact', 'icontains']
 }
`

but when I try to query, like this : 
`
{
    cities(kind_In: ["PPLC", "PPLA"]
}
`
it shows that Graphene is waiting kind__In be a String, but I do the same as a string, and it doesn't filter to what I need (actually with args as "['PPLC','PPLA']". and data comes empty)

Can anyone help me :) would be appreciated.

**Comment by earlgreyz** [comment]
I don't know how about Django, but you might do it manually

```python
class Query(graphene.ObjectType):
    cities = graphene.List(City, kind__in=graphene.List(graphene.String)
    def resolve_cities(self, args, context, info):
        query = # Get django query
        kind__in =  args.get('kind__in', None)
        if kind__in:
           # Apply django in filters
        return query
```

**Comment by mjmonroe** [comment]
We have the same use case. GraphQl is not a query language and does not natively support nested queries. The _graphene.InputObjectType_ can be used to create your own JSON format that supports nested queries. The code then reads the JSON and translates it into django _Q_ objects. We are using [MongoEngine's ](http://mongoengine.org/) _Q_ objects, which are based on django's.

In our case we have a _filter_ input which is a self referencing _graphene.InputObjectType_. Self referencing because you can nest the query as deep as you want. Each _filter_ level represents a single nesting level. The linkage between a _resolver_ and a query is broken because a single _InputObjectType_ can be used to query any field in the database. By breaking the linkage, we allow for abritary 'AND'/'OR' combinations of any depth with any field in the database. For instance, a field can be queried on, but never returned by GraphQl. The search model is completely decoupled from the GraphQl domain model. Now that they are separate, they can evolve separately. Different views of the data can be generated and returned by GraphQl, all based on the same query.

### Example Filter InputObjectType
| Input | Description |
| ------ | -------------|
| op | Enum: Operator to apply at current level |
| content | [Filter]: List of filters to apply underneath current level. Only valid for logic operators 'AND', 'OR', 'MATCH'. This is self referencing, filters contain lists of more filters.  |
| field | String: Field to apply operator on. Not valid for 'AND' and 'OR' operators. |
| value | [String]: Value is what a field is compared to, << field >><< op >><< value >>. Not valid for logic operators. |
| negate_op | Boolean: Negate the operator by adding a programatic 'not' |

```graphql
query ExampleFourNesting {
    result(filter: {
        op: OR,
        content: [{
                op: AND,
                content: [{
                        op: eq,
                        value: ["4"],
                        field: "some_field"
                    }, {
                        op: gt,
                        value: 16,
                        field: "another_field"
                    }

                ]
            }, {
                op: exact,
                value: "some_value",
                field: "another_field"
            }
        ]
    }) {
        hits {
           stuff
        }
        pagination {
            count
            pages
            page
            size
        }
    }
}
```

**Comment by jkimbo** [comment]
Hi @minrock . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by sulabhjain** [comment]
> We have the same use case. GraphQl is not a query language and does not natively support nested queries. The _graphene.InputObjectType_ can be used to create your own JSON format that supports nested queries. The code then reads the JSON and translates it into django _Q_ objects. We are using [MongoEngine's ](http://mongoengine.org/) _Q_ objects, which are based on django's.
> 
> In our case we have a _filter_ input which is a self referencing _graphene.InputObjectType_. Self referencing because you can nest the query as deep as you want. Each _filter_ level represents a single nesting level. The linkage between a _resolver_ and a query is broken because a single _InputObjectType_ can be used to query any field in the database. By breaking the linkage, we allow for abritary 'AND'/'OR' combinations of any depth with any field in the database. For instance, a field can be queried on, but never returned by GraphQl. The search model is completely decoupled from the GraphQl domain model. Now that they are separate, they can evolve separately. Different views of the data can be generated and returned by GraphQl, all based on the same query.
> 
> ### Example Filter InputObjectType
> Input	Description
> op	Enum: Operator to apply at current level
> content	[Filter]: List of filters to apply underneath current level. Only valid for logic operators 'AND', 'OR', 'MATCH'. This is self referencing, filters contain lists of more filters.
> field	String: Field to apply operator on. Not valid for 'AND' and 'OR' operators.
> value	[String]: Value is what a field is compared to, << field >><< op >><< value >>. Not valid for logic operators.
> negate_op	Boolean: Negate the operator by adding a programatic 'not'
> ```graphql
> query ExampleFourNesting {
>     result(filter: {
>         op: OR,
>         content: [{
>                 op: AND,
>                 content: [{
>                         op: eq,
>                         value: ["4"],
>                         field: "some_field"
>                     }, {
>                         op: gt,
>                         value: 16,
>                         field: "another_field"
>                     }
> 
>                 ]
>             }, {
>                 op: exact,
>                 value: "some_value",
>                 field: "another_field"
>             }
>         ]
>     }) {
>         hits {
>            stuff
>         }
>         pagination {
>             count
>             pages
>             page
>             size
>         }
>     }
> }
> ```

We have similar issue coming from lucene world where we would like to support nested AND or OR operations. It will be great to get this request considered in future roadmap. Thanks

**Comment by julianmoji** [comment]
@mjmonroe Can you tell me please which are your libraries versions?
