### ISSUE TITLE
Problems debugging with vscode

### ISSUE THREAD

**Issue by ramarivera** [graphql-python/graphene#616]
First of all, I would like to say what a great librarie this is. As @mandx mentioned in #614 , it allows me to use python while speeding up frontend development. So Thanks!!

Now, to my question/problem/issue:  I'm just learning graphene, with the goal of (maybe) one day in the near future writing an integration with  MongoEngine, as this is what I need to use for persistence in the project I'm working on. Thing is, to understend a little whats going on behind the curtains, I executed the sqlalchemy flask example (inside VScode) and set up some breakpoints (inside querys, resolvers, etc) but none of them were triggered. 

Is there a reason for this? or a workaround? I've read in #451 that someone else has a similar problem, but i couldnt find a reason/workaround.

Thanks!

**Comment by mandx** [comment]
Are you able to debug any Python code at all? If instead of breakpoints, you add `print()` statements do they show up in your terminal?

Personally, I don't use my editor to debug any Python code, what I do is install [IPython](https://pypi.python.org/pypi/ipython/) and [PuDB](https://pypi.python.org/pypi/pudb/) (inside the virtualenv, if any) and simply add this line `import pudb; pudb.set_trace()` to make PuDB pop up at that line.

At the very least, `print()` statements should appear in your terminal. If they do, then the problem might be your VSCode setup. First try debug with VSCode a simple hello world Python program, then try with your Flask/Graphene app.

**Comment by ramarivera** [comment]
No, print statements do not show.
Yes, I can and have debugged other Python code using vscode.
Thanks

**Comment by mandx** [comment]
Try this then: Add print statements inside code blocks that *you know* it is executed. If those print statements show up, then place breakpoints at those print statements, then try again.

**Comment by jkimbo** [comment]
Hi @ramarivera . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by ramarivera** [comment]
Hello @jkimbo . No problem, Unfortunately i haven't worked with graphene for a long time due tu school and work stuff, so I cant remember if i ever solved it. Close away,
