### ISSUE TITLE
Mutation.Field() should pass through (non-argument) params

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphene#634]
Currently, a param such as `name` is swallowed. Pull request desired?

https://github.com/graphql-python/graphene/blob/master/graphene/types/mutation.py#L78

**Comment by wesdyoung** [comment]
`graphene.types.mutations.Mutation.Field` doesn't pass on it's `*args` or `**kwargs` to the  `graphene.types.fields.Field` constructor.  Is this by design or a bug?  If by design I feel this should be changed to at least allow the `description` argument to be passed to the `graphene.types.fields.Field` constructor.

My current work around is to set the description attribute on the mutation field after an instance has been created.

**Comment by dfee** [comment]
@wesdyoung alternatively, you can just construct the ObjectType as any other object type and add it to your mutation using graphene.Field(). the Mutation wrapper simply creates an InputObjectType from the args and does just that.
