### ISSUE TITLE
Missing docs on `mutate_and_get_payload()`?

### ISSUE THREAD

**Issue by bkeating** [graphql-python/graphene#659]
Maybe I'm just not looking in the right place, but I can't seem to find any documentation on `mutate_and_get_payload()`. I use `mutate()` until I realized I saw others using `mutate_and_get_payload` so I went to look it up and couldn't find anything (but the actual source). Thought I'd mention it here.

**Comment by alexisrolland** [comment]
I did not even know there was such a method so I agree with you that documentation about mutations in general is lacking.

For this reason I have documented the way I do it here on this link: https://github.com/alexisrolland/flask-graphene-sqlalchemy/wiki/Flask-Graphene-SQLAlchemy-Tutorial#add-graphql-mutations

I’m not sure if that’s a good way to do mutations but it works for me.

**Comment by djm** [comment]
Agreed, this should have proper documentation but I'll leave this here for anyone landing here from Google:

`mutate_and_get_payload()` is only available to override if you are subclassing `[relay.ClientIDMutation](http://docs.graphene-python.org/en/latest/relay/mutations/#mutations)` and you should only be doing this if you're working with `Relay` on the frontend.

`Relay` requires a specific payload syntax for queries and mutations and thus subclassing `relay.ClientIDMutation` rather than the standard `graphene.Mutation` abstracts away a lot of the extra work required.

The method is different because of `graphene` design decisions, if you take a look [at the code](https://github.com/graphql-python/graphene/blob/d65e4316195e793b2b4e86f7b0ccc98daa4686c7/graphene/relay/mutation.py#L68) you can see that the normal `mutate()` has a bunch of wrapping logic and calls `mutate_and_get_payload()` within that flow.
