### ISSUE TITLE
Proposal: Change the `required` argument of a scalar to be `True` by default

### ISSUE THREAD

**Issue by anisjonischkeit** [graphql-python/graphene#668]
I believe that the `required` argument for graphene Scalars should be True by default.

Imagine I have this mutation:

```
class DoMutation(graphene.Mutation):
    class Arguments:
        name = graphene.String()

    ok = graphene.Boolean()

    def mutate(self, info, name):
        # mutate
        return DoMutation(ok=True)
``` 

This will work whenever a value is provided to `name`, however will fail with a python exception if no `name`. If you don't know to look out for this, and you forget to test the program passing in no name you won't ever spot this bug.

the fix ofcourse is to set a default value for the name argument in the mutate function however this means the user has to remember that name could be undefined and check it everytime. This is not a reliable solution. It would be better instead to say that an argument is always required unless explicitly stated that it isn't. If a developer intentionally sets a `required` to False, he will think about "what if the value is not there" and set a default. If he doesn't set the value, he will not think about it and so we should assume the safest option. Also with most Arguments they should probably actually be required, even if they currently are not

**Comment by jkimbo** [comment]
@anisjonischkeit I think this is issue is happening because there is a semantic difference in the GraphQL specification between an argument that is `null` vs one that is not defined: http://facebook.github.io/graphql/October2016/#sec-Null-Value That is why when `name` is not defined, in your example, it is not passed to the `mutate` method at all.

The way to work around that is to use kwargs:

```python
class DoMutation(graphene.Mutation):
    class Arguments:
        name = graphene.String()

    ok = graphene.Boolean()

    def mutate(self, info, **args):
		name = args.get('name', None)
        # mutate
        return DoMutation(ok=True)
```

I don't think changing the default value of the `required` attribute is a good idea since it will be diverging from the GraphQL specification.
