### ISSUE TITLE
When default_value effect?

### ISSUE THREAD

**Issue by yywing** [graphql-python/graphene#757]
```python
class TestInputType(graphene.InputObjectType):
    timeout = graphene.Int(default_value=3000)
```
If I do not add 'required=True',  execute 'timout=None', I will get a None
If I add 'required=True', execute ' timeout=None', I will get a error " Expected "Int!" "

I think when 'timeout=None' , this 'timeout = graphene.Int(default_value=3000, required=True)' should get 'timeout=3000' 

If this field is nullable, it can be null. If this field is not nullable, but  get null, should default value effect?

**Comment by dan98765** [comment]
My expectations for this situation would be: 
If your field `timeout` on InputObjectType is nullable & has a default_value defined. If `timeout=None` is passed by the user then I think the user's explicit passing of None should be respected and the default_value not take effect. The value is None. However, if the user omits passing the argument `timeout` completely then I think the default_value should take effect. 

If `timeout` is not nullable & has default_value defined, then as a user I prefer that if I were to explicitly do `timeout=None` it would error because it probably means there's a bug in my code that resulted in None getting passed instead of an integer. I believe this is how it currently works.

**Comment by yywing** [comment]
I understand what you said.
‘’‘Arguments can be either required or optional. When an argument is optional, we can define a default value - if the unit argument is not passed, it will be set to METER by default.’‘’
And I found this in graphql Document.

But, I think if timeout is not nullable & has default_value defined, it should get default_value when ```timeout=None```.
Or, ```default_value``` is useless, it is only used when nullable and not passed value.

**Comment by dan98765** [comment]
@yywing I'm not part of the graphql-python team so I can't speak for them and their design decisions. However, I would say that the current behavior around default & required values seems to follow the same pattern as swagger/openapi, which is quite large & respected.

Specifically, check out https://swagger.io/docs/specification/describing-parameters the section on "Required and Optional Parameters". In the "Common Mistakes" section:

> There are two common mistakes when using the default keyword:
> Using default with required parameters or properties, for example, with path parameters. This does not make sense – if a value is required, the client must always send it, and the default value is never used.

**Comment by yywing** [comment]
@dan98765  Thanks！
