### ISSUE TITLE
Add Authorization header to Graphene Client

### ISSUE THREAD

**Issue by benwis** [graphql-python/graphene#766]
Is there an easy way to add an authorization header to the graphene.test Client command? I'm doing unit tests, and I need to be able to send commands while logged in. If not, can you provide guidance on the best way to do this?

**Comment by jkimbo** [comment]
@benwis when using the test client you can pass `context_value` to the `execute` call: http://docs.graphene-python.org/en/latest/testing/#execute-parameters

That allows you to pass authorization headers to the query execution.

**Comment by kawasakikou** [comment]
How can I do this?
        
    executed = client.execute(current_user_query, context_value={'Authorization': header})

This gives the following result

    {'errors': [{'message': "'NoneType' object has no attribute 'fields'"}], 'data': None}

**Comment by jkimbo** [comment]
@kawasakikou I'm not sure that what that error is. Can you provide a reproducible example?

**Comment by anudeepsamaiya** [comment]
@jkimbo can you express your opinion on this issue also #942.

**Comment by thanhpd-teko** [comment]
> @benwis when using the test client you can pass `context_value` to the `execute` call: http://docs.graphene-python.org/en/latest/testing/#execute-parameters

Hi, can you give me example how to pass headers into graphene client, i can not find  any document about it. Thanks.

**Comment by jkimbo** [comment]
@thanhpd-teko Graphene does not have a concept of HTTP headers because it is not a web framework but a way of executing graphql queries. If you are using something like [graphene-django](https://github.com/graphql-python/graphene-django) then the `info.context` value in your resolvers will be the Django request object. So in your tests you can replicate that by passing a mock request object to the `context` param. You can create a mock request object using the Django [request factory](https://docs.djangoproject.com/en/2.2/topics/testing/advanced/#the-request-factory).

**Comment by jritsema** [comment]
Hi there...new to this community.  Are you saying that if using this library as a graphql client, it does not support passing http headers to the server?  Sorry, I'm a bit confused.  Thanks.

**Comment by jkimbo** [comment]
@jritsema this library is not a graphql client, it's a graphql server only. The above discussion was explaining how to pass headers in the Graphene *TestClient* which is a helper that can be used to test your graphene server not actually make graphql api calls.

If you need a graphql client in python you could try using: https://github.com/graphql-python/gql

**Comment by jritsema** [comment]
Thanks for the explanation @jkimbo!

**Comment by fabianriewe** [comment]
Hey, I was having troubles with this issue too. I just want to post my solution so anyone having the same problem will find a way to solve it. I didn't know that I had to send a `request` inside the context. The documentation was not clear about this.

```python
from flask import request

token = 'Bearer ' + get_access_token()
request.headers = {'Authorization': token}
client.execute(query, context_value=request)
```

**Comment by chidimo** [comment]
For anyone using pytest-django you can pass extra headers to `graphql_query` like so.

```python
from graphene_django.utils.testing import graphql_query

@pytest.fixture
def client_query(client):
    def func(*args, **kwargs):
        return graphql_query(*args, **kwargs, client=client, headers={'HTTP_WHATEVER': 'some value'})

    return func
```

Note that (unlike how you pass headers on the client side) you have to prefix the header (in this case) with `HTTP_`. In this way you can be able to access it in your query or mutation as

```python
def resolve_some_value(self, info, **kwargs):
    value = info.context.META.get('HTTP_WHATEVER')
```

**Comment by plopd** [comment]
Dear @chidimo,

can you be more clear on your comment

> (unlike how you pass headers on the client side)

1. Can you explain _why_ I need to prefix the value in the Headers with `HTTP_` ?
2. What is the `client` variable?

Can you provide a minimal working example?

**Comment by chidimo** [comment]
@plopd , I see that phrase is not very clear. What I meant is this.

Let's say you want to pass a header, `"is-some-header"`. In apollo client (on the frontend app) you simply specify it in the header section as `{ ...other-stuff, "is-some-header": "some value" }`.  Then on the backend it is available as `HTTP_IS_SOME_HEADER`. But in the case of pytest-django, you have to specify the same header in the exact format that the backend is going to expose i.e. `HTTP_IS_SOME_HEADER`, instead of how you do it in the apollo frontend app, `"is-some-header"`.

Hope that helps.

**Comment by samarthgowda96** [comment]
i'm just trying to pass HTTP_AUTHORIZATION cognito token to test all my queries and mutations and just getting an error token has not been passed since it needs to get the context of logged in user, i just want to pass hard coded token for now in the Graphene test client query, Any leads appreciated , Thanks :) heres is what i'm trying to achieve:
 ```
class PostTest(TestCase):

  def getAllPosts(self):
    client = Client(schema)
    self.assertMatchSnapshot(client.execute(
    """
    query{
          getPost(first:10){
            edges{
              node{
                title
                description
                isLiked
           }
          }
        }
      }
     
   """,
    context = {"HTTP_AUTHORIZATION:"**HERE IS THE COGNITO GENERATED TOKEN**"}


   ))
```
