### ISSUE TITLE
Middleware example fails in doc

### ISSUE THREAD

**Issue by leebenson** [graphql-python/graphene#812]
From http://docs.graphene-python.org/en/latest/execution/middleware/#example:

```py
class AuthorizationMiddleware(object):
    def resolve(self, next, root, info, **args):
        if info.field_name == 'user':
            return None
        return next(root, info, **args)
```

Results in:

> graphql.error.located_error.GraphQLLocatedError: resolve() missing 1 required positional argument: 'info'

It was only due to stumbling across #612 that I read this:

> self not being a class instance in resolver 'methods'. I don't understand the architectural reasons why this can't be the case, but in Python an instance method (like the resolver methods) is expected to take a self first argument. The documentation says that this isn't the case with Graphene (which is unexpected), but it still calls the argument self in some cases which further confuses the issue. It is mentioned that these methods act like static methods, however it's unexpected that they aren't decorated with the `@staticmethod` decorator.

Which works:

```py
class AuthorizationMiddleware(object):
    def resolve(next, root, info, **args): # remove `self` as first param
        if info.field_name == 'user':
            return None
        return next(root, info, **args)
```

**Comment by jkimbo** [comment]
@leebenson good spot! Could you submit a PR that fixes it? You can find instructions on how to build the docs in the README: https://github.com/graphql-python/graphene#documentation

**Comment by dani0805** [comment]
just made a PR for the middleware documentation covering its configuration in settings.py https://github.com/graphql-python/graphene/pull/820
Placing it here for lack of better ideas

**Comment by morenoh149** [comment]
@dani0805 sounds like the PR fixing this issue is out of scope for this repo? catch-22? If so we should just close this issue as unfixable.

**Comment by riverfr0zen** [comment]
Doesn't look like this has made it into the docs yet at https://docs.graphene-python.org/en/latest/execution/middleware/

**Comment by AlexEshoo** [comment]
The documentation still shows the old signature for the resolve method on middleware classes.
I also find the signature as defined in the PR here to be a bit strange, does the first parameter of the method get overloaded? Having it not be `self` (not just not calling it that, but also it appears to *replace* the argument with the `next` partial function instead of it being a reference to the instance of the class) just does not feel intuitive, and as far as I can tell it completely nullifies any benefit to using a class rather than a function for the middleware.
