### ISSUE TITLE
Best Practices for permission and filtering in middleware

### ISSUE THREAD

**Issue by antoine-gallix** [graphql-python/graphene#878]
I'm trying to implement permission and filtering in a middleware, depending of the logged-in user.

The documentation on middleware is very limited, and I can't find anywhere any suggested good practive on how to implement middleware functions for those purposes.

In case of trying to restrict the user access to certain fields or types, I have some code in a middleware function that check access rules depending on the queried ObjectType and the user roles. Some things are missing in the documentation to do this.

- How can I cleanly abort the resolution of a field, or of the query altogether and send an error message instead.
- Is there a recommended way to structure errors messages?
- In case of filtering, I want to limit access to certain objects or only to certain records in the collection. Is the middleware the right place to do that? How can I limit the results of a list fields to certain elements without returning error message?

**Comment by antoine-gallix** [comment]
Ok thank you for the advice!

**Comment by tobiasfeil** [comment]
@jkimbo the link you posted suggests that the resolver, by help of the business logic layer, returns either the object requested or `null`, aka `None`, if not authorized. But I don't know how to translate this to Graphene, because I always have to return an ObjectType, so if my resolver looks like this
```
def resolve_user(root, info, id_of_user_to_get_info_about):
    return User(...)
```
the resolver always has to return a User object, even when not authorized. Isn't this in contrast to the official GraphQL spec?

**Comment by jkimbo** [comment]
@tobiasfeil it depends on if your field is required or not. If it is not required then it is perfectly valid to return `None`.
