### ISSUE TITLE
Proposal: explicitly declaring resolvers with decorator

### ISSUE THREAD

**Issue by DrPyser** [graphql-python/graphene#898]
```
class MySecondAttempt(ObjectType):
    name = String()
    age = Int(required=True)
        
    @name.resolver
    def resolve_name(self, ...): ...

    @age.resolver
    def resolve_age(self, ...): ...
```
 Explicit is better than implicit.

The resolvers could have any arbitrary name, and could also be defined before or after the class definition. Resolvers could still be defined using the `resolver_` prefix convention if the explicit decorator isn't used.

**Comment by dvndrsn** [comment]
I really like the idea of declaring resolvers with a decorator. There are a couple of patterns that are possible tho. A pattern that I stumbled across recently works pretty well for declaring functions alongside their schema definition. Maybe we should do an evaluation of different approaches?

Here's a type with both default and custom resolvers for fields, using a decorator pattern for declaring custom resolvers and schema at the same time.

```python
class StoryType(graphene.ObjectType):

    class Meta:
        interfaces = (graphene.Node, )
        possible_types = (models.Story, )

    title = graphene.String(description='stuff')
    subtitle = graphene.String()
    description = graphene.String()

    @resolves(graphene.String)
    def published_year(story: models.Story, info: graphene.ResolveInfo) -> str:
        return str(story.published_date.year)
```

The decorator implementation is pretty simple:

```python
def resolves(field, *args, **kwargs):
    def decorate(resolver_function):
        return field(*args, **kwargs, resolver=resolver_function)

    return decorate
```

I don't expect that this would break any of the existing Field API. The only strange thing about this approach is that it is a little unexpected that we define a function and our decorator replaces that function reference with a reference to an Field object that contains that function reference, but it makes for pretty clean Graphene code. You also can't use this decorator on a function outside of a your ObjectType class.

**Comment by DrPyser** [comment]
Why couldn't you use this decorator outside of an `ObjectType` class?

Also, one way to avoid the problems and weirdness of changing a function into a field, would be to make fields implement the callable interface(`__call__`) to behave like the resolver function.

**Comment by dvndrsn** [comment]
This decorator returns a field, which wouldn't be helpful outside of an `ObjectType` class since it wouldn't bind to our schema. We would have to assign that field to an ObjectType to use it.

```
@resolves(graphene.String, description='A field with no schema')
def name_field_with_resolver(root, info):
    return 'Bob'
# name_field_with_resolver = graphene.String(...)

class Person(graphene.ObjectType):
     name = name_field_with_resolver    
```

Seems a little clumsy and I'm not sure if there is any implication of re-using a field definition in multiple `ObjectType`..

If you want to bind functions outside of the `ObjectType` back to our field, you could have a decorator on the field itself, more in line with your original proposed pattern.

```
class Person(graphene.ObjectType):
    name = String()

@Person.name.bind_resolver
def my_resovler_outside_the_object(root, info):
    return 'Bob'
```

I think the implementation for this decorator is also pretty straightforward.

```
class Field:
    # ...
    def bind_resolver(self, resolver_method):
         self.resolver = resolver_method
         return resolver_method  # return the original method undecorated.
```

Not too shabby. You could stack multiple `bind_resolver` decorators on the same function even, since we're returning the method unmodified.

Implementing `__call__` on our field would fix that weirdness of a function becoming a class, that's a good thought. Though I don't know what the implications of our field instance being callable might be. All fields are set as class attributes, which are hidden if you create an instance of an `ObjectType` like `Person(name='Bob')`. Maybe it wouldn't be an issue?

```
def resolves(field_type, *args, **kwargs):
    def decorate(resolver_function):
        field = field_type(*args, **kwargs, resolver=resolver_function)
        # monkey patch call onto the field instance to make it Callable
        field.__call__ = lambda *args, **kwargs: field.resolver(*args, **kwargs)
        return field

    return decorate
```

Quick monkey patch approach here, not sure if making a change to `Field` base class to make it Callable is a better idea or what the implications of that change might be.

**Comment by DrPyser** [comment]
@dvndrsn Yeah, `__call__` has to be defined as an instance method in the class. Just assigning a lambda on the instance like that won't work.

As far as I can tell, the only implication of defining a `__call__` method in the base `Field` class, would be to allow fields to be used as callables. The only way I can think of that could require care, is if some code currently expects a callable or `Field`, and behaves differently depending on which it gets, and checks for a `callable` first.
