### ISSUE TITLE
graphene + flask how to return images

### ISSUE THREAD

**Issue by kutabale** [graphql-python/graphene#909]
What i am  looking for is how to return an image for a query.
Is there anything build in graphene that handles byte arrays. 
Also i noticed JSONString scalar, can i use this to return an encoded image as json?

**Comment by messa** [comment]
If you really need to return binary data then simplest solution would be (I think) to encode them using base64 to a String value. GraphQL usually returns data as JSON and JSON itself does not support binary data.

But maybe it would be better to return just URL of the image in the query response :)

**Comment by BossGrand** [comment]
You can also upload to something like aws's s3 and send the url back

**Comment by vreddhi** [comment]
returning URL would results in a redirect response and not the content itself. We definitely need a better way to handle or serve binary data.

**Comment by ekampf** [comment]
If you really need to return binary data the way would be to base64 encode it into a `String` field.
(You could derive from `Scalar` and implement your own `Baqse64String` that encode bytes to\from base64)
There's no other way because JSON\JS don't have a better data type :)
That kind of response will not result a redirect...
