### ISSUE TITLE
Remove README.rst

### ISSUE THREAD

**Issue by morenoh149** [graphql-python/graphene#915]
The project has README.md and README.rst files. Updating the readme requires making sure you change both files. Remove one.

**Comment by Cito** [comment]
I guess the README.rst was for PyPI an dthe README.md for GitHub.

As far as I know GitHub now understands README.rst as well, and on the other hand PyPI now also understands README.md when you set `long_description_content_type="text/markdown"` in setup.py. So in fact one of them should be removed, but make sure everything still looks nice in both GitHub and PyPI.

**Comment by vreddhi** [comment]
Is anyone working on this? If not i can start with this minor change or update.

**Comment by morenoh149** [comment]
@vreddhi go for it. It's a toss up. I prefer markdown.

**Comment by vreddhi** [comment]
I agree, let me checkout a branch and remove the restructuredtext, as it is more safe to have markdown, and we need not have redundant data in two places.

I say it is more safe because of additional guideline given in pypi documentation regarding restructuredtext.
https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup
