### ISSUE TITLE
Internal complexity

### ISSUE THREAD

**Issue by rafales** [graphql-python/graphene#92]
Internal implementation of graphene seems to be overly complicated - Inheritance graph looks insane. Are there any plans to simplify it?

**Comment by syrusakbary** [comment]
Hi @rafales, thanks for asking this!

`graphene` principal focus at the beginning was the syntax and the way you use it.
However, as you mentioned, there are things that could be simplified. And there are others that it's not as easy to simplify when you have support for multiple schemas.

As the code-coverage and testing is quite good, it's easy to do internal refactors (it's been three massive internal refactors since we launched in October)

I would work on this in the long-term run, but any suggestion on what you think could be simplified or pull request for simplifying `graphene` will be always welcome :wink:

**Comment by rafales** [comment]
Depends on the requirements.

For example syntax where we can define scalar fields without the need to use `Field` instance looks a bit nicer but is probably one of the causes for additional complexity and is misleading, especially at the beginning. Are you open to changing that to more sqlalchemy-like style? Or is this the syntax we want and all we can do is change the internals?

**Comment by syrusakbary** [comment]
When we launched, the way we approached was very similar to SQLAlchemy/Django.

You have to create a Field and then a Type, like:
```python
class User(graphene.ObjectType):
    name = graphene.StringField()
```

But the main usage problem arises when you want to use a String as a Argument too (not only as a Field). So naming `StringField` for and `Argument` was not very intuitive.
So then, we switched to:

```python
class User(graphene.ObjectType):
    name = graphene.Field(graphene.String(), my_arg=graphene.Argument(graphene.String()))
```

However we were not as confortable as we should with this last approach, as is much more verbose.

Apart from that, this approach was working for `SQLAlchemy` as mostly the only time you use a type is in a `Column` function, however in `GraphQL` a field is another kind of type.
So we decided to simplify to this:

```python
class User(graphene.ObjectType):
    name = graphene.String(my_arg=graphene.String())
```

Which is much more easier to read and develop, so we adapted the code internally for make it work.
We also make sure that the previous way -and more verbose- was also working.

However if you have idea that could make it better I'm quite open for discussing and improving `graphene` for the benefit of all :)

**Comment by syrusakbary** [comment]
I'm going to close this issue, please reopen it if you have any idea for simplifying the internal code or want to discuss it further! :)
