### ISSUE TITLE
What is the status of graphene and the related integrations regarding graphql-core-next?

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphene#954]
Is there some clear documentation regarding the relationship between graphql-core-next and graphene, graphene-django, etcetera? From the user perspective, things are pretty confusing right now, and digging through the various issues and discussions just seems to make it more so.

I'm looking for the canonical location to review the status of the ecosystem, and not finding it. If it doesn't exist, it would likely help a lot of folks get there heads around what's what.

**Comment by Cito** [comment]
@chengling The graphql-python ecosystem is undergoing a transition right now and things are still in a state of flux. Syrus Akbari, who created most of it, handed the responsibility for maintaining the projects and further development over to various people in the community. You can find the details in #884 which also has a link to a Slack channel where we are trying to coordinate everything and push things forward. If you want to engage further please join us there - every help is welcome.

Graphene and most other tools currently use [graphql-core](https://github.com/graphql-python/graphql-core) as fundament, which has been created as a Python version of the reference implementation [GraphQL.js](https://github.com/graphql/graphql-js). However, it was based on version 0.6 of that library and has not been kept in sync since that, and also was created with Py2 in mind, therefore doesn't use newer features like type hints and async/await syntax. That's why I created [graphql-core-next](https://github.com/graphql-python/graphql-core-next/) as a more modern Python-3-only version that makes use of all the new features. It is also up-to-date with the current version 14.2.1 of GraphQL.js and will be kept in sync with it in the future. The idea is to move the whole ecosystem to graphql-core-next as the new fundament. See also graphql-python/graphql-core#241.

**Comment by johndunderhill** [comment]
@cito can you explain why it was necessary for graphql-core-next to become Python 3 only in order to bring it up-to-date with the reference implementation written in Javascript?  Thanks!

**Comment by Cito** [comment]
@johndunderhill that was not necessary.  I just wanted to write a cruft-free, modern port of GraphQL.js that makes use of the new Python features (see also the [README](https://github.com/graphql-python/graphql-core-next/) regarding the goals). It would be possible to create a Py2-compatible version of graphql-core-next and in fact Syrus had already worked on that some time ago in the graphql-core/modern branch. However, currently there is nobody who wants to maintain that branch and keep it up to date, and Py2 EOL is near anway.
